name: Sync Notion Posts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # 매시간 실행

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        run: |
          npm install @notionhq/client notion-to-md gray-matter dotenv

      - name: Run Notion Sync
        run: node notion-sync.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_IDS: ${{ secrets.NOTION_DATABASE_IDS }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install Jekyll Dependencies
        run: |
          bundle install

      - name: Build Site with Jekyll (including categories)
        run: |
          bundle exec jekyll build -d "_site"
        env:
          JEKYLL_ENV: "production"

      - name: Commit & Push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "sync: update posts from Notion" || echo "No changes"
          git push
